name: foot-terminal
version: '1.14.0'
summary: A fast, lightweight and minimalistic Wayland terminal emulator
description: |
  ssh can be used to escape from the snap's confined environment. ssh keys directory is /home/᚜user᚛/snap/foot-terminal/common/.ssh/

  For autoconnection put to your /home/᚜user᚛/snap/foot-terminal/common/.config/foot/foot.ini something like this:  
  shell=ssh -t user@localhost tmux -u new -A

  Also this snap allows to activate the terminal emulator by opening any character device: xdg-open /dev/tty
source-code: https://github.com/iomezk/snap-foot/tree/core22-confined
license: MIT
base: core22
confinement: strict
grade: stable
icon: icon.svg

apps:
  foot-terminal:
    command-chain:
    - foot-wrapper
    command: bin/foot
    plugs:
    - network
    - opengl
    - wayland

environment:
  HOME: $SNAP_USER_COMMON
  PATH: $SNAP/bin:$PATH
  LD_LIBRARY_PATH: $SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
  FONTCONFIG_PATH: $SNAP/gui-lib/etc/fonts
  FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf

plugs:
  gnome-42-2204:
    interface: content
    default-provider: gnome-42-2204
    target: $SNAP/gui-lib

layout:
  /usr/share/font1:
    symlink: $SNAP/gui-lib/usr/share/fonts
  /usr/share/X11:
    symlink: $SNAP/gui-lib/usr/share/X11

package-repositories:
- type: apt
  formats:
  - deb-src
  components:
  - main
  suites:
  - jammy-updates
  key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
  url: http://archive.ubuntu.com/ubuntu

parts:
  local:
    source: snap/local/
    source-type: local
    plugin: dump
    prime:
    - -patches/
  foot:
    after:
    - local
    source: https://codeberg.org/dnkl/foot/archive/1.14.0.tar.gz
    source-checksum: sha256/9a306951bc6bdce150364bccb0fb4b67720f50e98e9ac1de89792c1c1aa30690
    source-type: tar
    plugin: meson
    build-packages:
    - meson
    - pkg-config
    - libpixman-1-dev
    - wayland-protocols
    - libwayland-dev
    - libxkbcommon-dev
    - libfontconfig1-dev
    - git  # for latest libtllist-dev
    - libfcft-dev
    - libharfbuzz-dev
    meson-parameters:
    - --buildtype=release
    - --strip
    - --prefix=/
    - -Dthemes=false
    - -Dime=false
    - -Dtests=false
    - -Dterminfo=disabled
    - -Ddefault-terminfo=xterm-256color
    override-pull: |
      craftctl default
      patch -p1 -i ../../local/src/patches/foot-default-theme.patch
      patch -p1 -i ../../local/src/patches/foot-ignore-args.patch
      patch -p1 -i ../../local/src/patches/foot-apparmor-flood.patch
    prime:
    - bin/foot
  ssh:
    after:
    - local
    plugin: nil
    build-packages:
    - dpkg-dev
    override-pull: |
      apt source openssh-client
      cd */
      patch -p1 -i ../../../local/src/patches/ssh-home-env.patch
      patch -p1 -i ../../../local/src/patches/ssh-apparmor-flood.patch
      apt build-dep -y openssh-client
      DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -B --no-sign -jauto
      mkdir "$CRAFT_PART_INSTALL/bin/"
      cp debian/openssh-client/usr/bin/ssh "$CRAFT_PART_INSTALL/bin/"
