name: foot-terminal
summary: A fast, lightweight and minimalistic Wayland terminal emulator
description: |
  ssh can be used to escape from the snap's confined environment. ssh keys directory is /home/$USER/snap/foot-terminal/common/.ssh/

  For autoconnection put to your /home/$USER/snap/foot-terminal/common/.config/foot/foot.ini something like this:  
  shell=ssh -t -o SendEnv=WAYLAND_DISPLAY user@localhost tmux -u new -A

  Also this snap allows to activate the terminal emulator by opening any character device: xdg-open /dev/random
source-code: https://github.com/iomezk/snap-foot/tree/core22-confined
license: MIT
base: core22
confinement: strict
grade: stable
icon: icon.svg

apps:
  foot-terminal:
    command-chain:
    - foot-wrapper
    command: bin/foot
    plugs:
    - network
    - opengl
    - wayland

environment:
  HOME: $SNAP_USER_COMMON
  PATH: $SNAP/bin:$PATH
  LD_LIBRARY_PATH: $SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
  FONTCONFIG_PATH: $SNAP/gui-lib/etc/fonts
  FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf

plugs:
  gnome-42-2204:
    interface: content
    default-provider: gnome-42-2204
    target: $SNAP/gui-lib

layout:
  /usr/share/font1:
    symlink: $SNAP/gui-lib/usr/share/fonts
  /usr/share/X11:
    symlink: $SNAP/gui-lib/usr/share/X11

package-repositories:
- type: apt
  formats:
  - deb-src
  components:
  - main
  suites:
  - jammy-updates
  key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
  url: http://archive.ubuntu.com/ubuntu

adopt-info: foot
parts:
  local:
    source: snap/local/
    source-type: local
    plugin: dump
    prime:
    - -patches/
  foot:
    source: https://codeberg.org/dnkl/foot/archive/1.16.2.tar.gz
    source-checksum: sha256/0e02af376e5f4a96eeb90470b7ad2e79a1d660db2a7d1aa772be43c7db00e475
    source-type: tar
    plugin: meson
    build-snaps:
    - gnome-42-2204-sdk
    build-packages:
    - git  # for latest libtllist-dev
    - jq
    build-environment:
    - PATH: /snap/gnome-42-2204-sdk/current/usr/bin${PATH:+:$PATH}
    - LD_LIBRARY_PATH: /snap/gnome-42-2204-sdk/current/lib/$CRAFT_ARCH_TRIPLET:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/gnome-42-2204-sdk/current/usr/lib:/snap/gnome-42-2204-sdk/current/usr/lib/vala-current:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    - PKG_CONFIG_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/lib/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
    meson-parameters:
    - --buildtype=release
    - --strip
    - --prefix=/
    - -Dc_args=-Wno-pedantic  # error: ISO C does not support the ‘_Float*’ type [-Werror=pedantic]
    - -Dthemes=false
    - -Dime=false
    - -Dtests=false
    - -Dterminfo=disabled
    - -Ddefault-terminfo=xterm-256color
    override-pull: |
      craftctl default
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/foot-default-theme.patch"
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/foot-ignore-args.patch"
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/foot-apparmor-flood.patch"
    override-build: |
      craftctl default
      craftctl set "version=$(jq -r .version meson-info/intro-projectinfo.json)"
    prime:
    - bin/foot
  ssh:
    plugin: nil
    build-packages:
    - dpkg-dev
    override-pull: |
      apt source openssh-client
      cd */
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/ssh-home-env.patch"
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/ssh-apparmor-flood.patch"
      apt build-dep -y openssh-client
      DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -B --no-sign -jauto
      mkdir "$CRAFT_PART_INSTALL/bin/"
      cp debian/openssh-client/usr/bin/ssh "$CRAFT_PART_INSTALL/bin/"
